### ISSUE TITLE
Add HazelCast support

### ISSUE THREAD

**Issue by fsjovatsen** [FINTlibs/fint-events#8]
Adde HZ support for event queue

**Comment by jarlehansen** [comment]
add common hazelcast.xml file that can be extended in the implementations. This should contain common config that can be overridden in the implementation,

` <hazelcast>
    <import resource="file:///etc/hazelcast/development-group-config.xml"/> 
    <import resource="classpath:development-network-config.xml"/>  
  </hazelcast>`

**Comment by jarlehansen** [comment]
Queue backup:

> By default, Hazelcast will make sure that there is one synchronous backup for the queue. If the member hosting that queue fails, the backups on another member will be used so no entries are lost.
Backups can be controlled using the following properties.
• backup-count: Number of synchronous backups, defaults to 1. So by default, no entries will be lost if a member fails.
• async-backup-count: Number of asynchronous backups, defaults to 0.
If you want increased high availability, you can either increase the backup-count or the async-backup- count. If you want to have improved performance, you can set the backup-count to 0, but at the cost of potentially losing entries on failure.

**Comment by jarlehansen** [comment]
Getting/putting items on queue:
http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/Queue/index.html

Listening for item events:
http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Events/Event_Listener_for_Members/Listening_for_Item_Events.html

**Comment by asgeirn** [comment]
Fixed in 7ffcfa56b951d88206f7f17975283b3e12e90561
